name: terminal-2048
base: core24
version: '0.1'
summary: Terminal-based 2048 game
description: |
  A simple, terminal-based version of the 2048 game.
  Use your arrow keys or WASD to move the tiles. The goal is to create a tile with the number 2048.

grade: stable
confinement: strict

parts:
  game:
    plugin: python
    source: .

apps:
  terminal-2048:
    command: bin/2048.py
