name: terminal-2048
base: core24
adopt-info: terminal-2048
summary: Terminal 2048 game
description: |
  A simple, terminal-based version of the 2048 game, now written in Rust.
  Use your arrow keys or WASD to move the tiles. The goal is to create a tile
  with the number 2048.

grade: stable
confinement: strict
icon: icon.svg
contact: https://github.com/kenvandine/terminal-2048/issues
issues: https://github.com/kenvandine/terminal-2048/issues
website: https://github.com/kenvandine/terminal-2048
license: GPL-3.0+
platforms:
  amd64:
  arm64:

parts:
  terminal-2048:
    plugin: rust
    source: .
    build-packages:
      - git
      - cargo
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10 || git rev-parse --short HEAD)
    override-build: |
      craftctl default
      cargo build --release --target-dir $CRAFT_PART_INSTALL/target
    prime:
      - target/release/terminal-2048

apps:
  terminal-2048:
    command: target/release/terminal-2048
